const ACTION_TYPES={
  COUNTER_INCREMENT: 'COUNTER_INCREMENT',
  COUNTER_DECREMENT:'COUNTER_DECREMENT',
  COUNTER_SET_STEP:'COUNTER_SET_STEP',

  CREATE_TASK:'CREATE_TASK',
  UPDATE_TASK:'UPDATE_TASK',
  REMOVE_TASK:'REMOVE_TASK',

  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  REMOVE_USER: 'REMOVE_USER',

  CREATE_HERO: 'CREATE_HERO',
  CREATE_HERO_REQUEST:'CREATE_HERO_REQUEST',
  CREATE_HERO_SUCCESS:'CREATE_HERO_SUCCESS',
  CREATE_HERO_ERROR: 'CREATE_HERO_ERROR',

  GET_HEROES: 'GET_HEROES',
  GET_HEROES_REQUEST: 'GET_HEROES_REQUEST',
  GET_HEROES_SUCCESS: 'GET_HEROES_SUCCESS',
  GET_HEROES_ERROR: 'GET_HEROES_ERROR',
}

export default ACTION_TYPES;